### PR TITLE
Update to ndarray 0.16

### PR DESCRIPTION
**Pull request by relf**
Updates `ndarray` dependency to work with current `ndarray 0.16`

### CODE REVIEW

**Comment by paulkernfeld** [comment]
Thanks for this PR! Will this still work with ndarray 0.7?

Paul Kernfeld
http://paulkernfeld.com

**Comment by relf** [comment]
Yes you're right. I was too quick, it works only for `ndarray 0.16`, as `into_shape_with_order` was introduced to replace the deprecated `into_shape`. How do you want to handle this? Just silence the deprecation warnings for now?

**Comment by paulkernfeld** [comment]
One possible solution would be to add in some kind of configuration that
can detect whether the new function is available and use that, maybe by
looking at what version of ndarray is in use. I don't know how to do that,
but I am guessing that it might work with macros. Another possible solution
would be to bump the dependency on ndarray and increment the version of
this crate. Another possibility would be to just let the warning be there
for now until it turns into an error in a future version of ndarray. I am a
little bit hesitant to silence the warning because it could serve a useful
purpose. What do you think about these possible solutions?

Paul Kernfeld
http://paulkernfeld.com

**Comment by relf** [comment]
Well, to keep backward compatibility I would just silence the warnings with a `#[allow(deprecated)]` where `into_shape()` is used, so you can simply release a `ndarray-csv 0.5.3` compatible with `ndarray 0.16`. 
Afterwards, it will be always possible to release a `ndarray-csv 0.6` which will be just compatible with `ndarray 0.16`. Or we could add a feature `ndarray_016` to implement conditional compilation with `#[cfg(feature = "ndarray_016")]` magic, but it requires more work to implement/document/use and it seems to me that you could wait for `ndarray 0.17` (which is nowhere near) to use such mechanism.

**Comment by paulkernfeld** [comment]
Okay, thanks for your patient and clear explanations, I think I'm starting to wrap my head around this although I still have more questions!

1. Is this warning showing us a real bug in the code, i.e. could the code return a wrong result depending on they layout of an array?
2. Why us it necessary to silence the warnings? As far as I can tell, the warnings don't actually cause the build to break. So, is this already compatible with ndarray 0.16 even if the warnings aren't silenced?

**Comment by relf** [comment]
> * Is this warning showing us a real bug in the code, i.e. could the code return a wrong result depending on they layout of an array?

As far as `ndrray-csv` is concerned, the warning is just a deprecation warning meaning that `into_shape()` will be removed in a future version of `ndarray`. If you want full details on the why such deprecation see [the related PR](https://github.com/rust-ndarray/ndarray/releases/tag/0.16.0) in the release notes. 

> 
> * Why us it necessary to silence the warnings? As far as I can tell, the warnings don't actually cause the build to break. So, is this already compatible with ndarray 0.16 even if the warnings aren't silenced?

No, the warning does not break the build but you do not want to clutter the compilations of downstream crates using your library with a warning they can not fix. Besides warnings are often considered as a failure in CI tests with `cargo clippy -- -D warnings`. We have been warned about the deprecation so we can just silence the warning for now waiting for the release of `ndarray 0.17` to deal with this.

**Comment by relf** [comment]
Forget about silencing the warnings, they are not seen by downstream users by default. So indeed we can just keep them, I am just used to considering them as errors in CI tests

**Comment by paulkernfeld** [comment]
That makes sense, thanks for checking that out! I'm good with ignoring the warnings until `.into_shape()` is removed.

Taking a quick look at the usages, I see that there are two kinds:

1. In the README, we declare a 2D array as an example. What if we created this array in a different way, e.g. using the `array!` macro?
2. In `lib.rs`, when we're reading the CSV file, we read the CSV file as a 1D array and then use `into_shape` to transform it into a 2D array. I agree that there's probably not an actual bug here because we are creating the array in `ndarray-csv` so it should always be in the default layout (row-major or "c" order, not column-major or "f" order). Looking back at the ndarray 0.7 docs, I agree there's not an obvious way to do the reshape that works in 0.7 and 0.16. One only slightly crazy solution is to rewrite the code so that it doesn't require a reshape at all, e.g. by writing each CSV row into the 2D return value one by one.

**Comment by paulkernfeld** [comment]
Thanks for this PR, and for your thoughtful analysis of the deprecation warnings!

**Comment by paulkernfeld** [comment]
Okay, I published this onto crates.io as v0.5.3

**Pull request merged**
